Wad 25 node infrastructure
SnickersVsMars/webapp-ws20-projects pull request #2
Opened 2020-11-26 19:17 UTC by lammia07

Create NodeJs infrastructure:
- express server
- config
- mysql
- routing

2020-11-26 20:48 UTC, m4rien0 requested changes

2020-11-26 20:48 UTC, m4rien0 commented on features/dbConnection.js
> +//...
remove?

2020-11-26 20:48 UTC, m4rien0 commented on features/dbConnection.js
> +// In unserem Fall 'connection' und 'handleError'
Change comment to english.

2020-11-26 20:48 UTC, m4rien0 commented on features/test/testRouter.js
> +// müssen hier 2 Router definieren.
Change comment to English.

2020-11-26 20:48 UTC, m4rien0 commented on features/test/testRouter.js
> +// Definieren der routen für die view files. In unserem fall sind dies plain HTML files
See previous comment.

2020-11-26 20:48 UTC, m4rien0 commented on features/test/testRouter.js
> +// In unserem fall im JSON Format
See previous comment.

2020-11-26 20:48 UTC, m4rien0 commented on features/test/testService.js
> +// Achtung in JS gibt es keinen private deklarator bei Klassen
Change comment to English.

2020-11-26 20:48 UTC, m4rien0 commented on features/test/testService.js
> +        dbConnection.select("Select * FROM tests", succes);
Would do all caps for SQL queries.
```suggestion
        dbConnection.select("SELECT * FROM tests", success);
```

2020-11-26 20:48 UTC, m4rien0 commented on features/test/testService.js
> +    get(succes) {
```suggestion
    get(success) {
```

2020-11-26 20:48 UTC, m4rien0 commented on features/test/testService.js
> +// Bedeutet es kann nur 1 Instanz des Service geben
Change comment to English.

2020-11-26 20:48 UTC, m4rien0 commented on package.json
> +  "version": "1.0.0",
```suggestion
  "version": "1.2.0",
```

2020-11-26 20:48 UTC, m4rien0 commented on package.json
> +  "description": "web application development projekt of the group SnickersVsMars for the FH-JOANNEUM",
```suggestion
  "description": "Education web application development project of the group SnickersVsMars for the FH-JOANNEUM",
```

2020-11-26 20:48 UTC, m4rien0 commented on package.json
> +  "author": "Michael Lamprecht",
```suggestion
  "author": "SnickersVsMars",
```

2020-11-26 20:48 UTC, m4rien0 commented on server.js
> +  console.log('Express server started at port 3000');
```suggestion
  console.log('Express server started on port ' + port);
```

2020-11-26 20:48 UTC, m4rien0 commented on server.js
> +  console.log('Express server started at port 3000');
Port should be from config file here as well (not hard coded).

2020-11-27 17:47 UTC, lammia07 commented on features/dbConnection.js
> +//...
remoed

2020-11-27 17:47 UTC, lammia07 commented on features/dbConnection.js
> +// In unserem Fall 'connection' und 'handleError'
translated

2020-11-27 17:47 UTC, lammia07 commented on features/test/testRouter.js
> +// müssen hier 2 Router definieren.
translated

2020-11-27 17:47 UTC, lammia07 commented on features/test/testRouter.js
> +// Definieren der routen für die view files. In unserem fall sind dies plain HTML files
translated

2020-11-27 17:47 UTC, lammia07 commented on features/test/testRouter.js
> +// In unserem fall im JSON Format
translated

2020-11-27 17:47 UTC, lammia07 commented on features/test/testService.js
> +// Bedeutet es kann nur 1 Instanz des Service geben
translated

2020-11-27 17:55 UTC, m4rien0 reviewed
Seems good :)

2020-11-27 17:56 UTC, merged